package com.example.governmentsubsidy.enums;

public enum ApplicationStatus {
    DRAFT,
    SUBMITTED,
    ELIGIBILITY_EVALUATED,
    FIELD_VERIFICATION,
    DISTRICT_REVIEW,
    FINANCE_APPROVAL,
    DISBURSEMENT_PLANNED,
    MILESTONE_PENDING,
    DISBURSEMENT_IN_PROGRESS,
    FULLY_DISBURSED,
    UTILIZATION_PENDING,
    COMPLETED,
    REJECTED,
    REVERIFICATION_REQUIRED
}
