export const APPLICATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  ELIGIBILITY_EVALUATED: 'ELIGIBILITY_EVALUATED',
  FIELD_VERIFICATION: 'FIELD_VERIFICATION',
  DISTRICT_REVIEW: 'DISTRICT_REVIEW',
  FINANCE_APPROVAL: 'FINANCE_APPROVAL',
  DISBURSEMENT_PLANNED: 'DISBURSEMENT_PLANNED',
  MILESTONE_PENDING: 'MILESTONE_PENDING',
  DISBURSEMENT_IN_PROGRESS: 'DISBURSEMENT_IN_PROGRESS',
  FULLY_DISBURSED: 'FULLY_DISBURSED',
  UTILIZATION_PENDING: 'UTILIZATION_PENDING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  REVERIFICATION_REQUIRED: 'REVERIFICATION_REQUIRED',
};

export const STATUS_CONFIG = {
  [APPLICATION_STATUS.DRAFT]: {
    label: 'Draft Application',
    badgeClass: 'badge-draft',
    stepIndex: 0,
    color: '#64748b',
    description: 'Application details entered, pending formal submission by applicant.',
  },
  [APPLICATION_STATUS.SUBMITTED]: {
    label: 'Submitted',
    badgeClass: 'badge-submitted',
    stepIndex: 1,
    color: '#0284c7',
    description: 'Application officially submitted. Ready for automated eligibility scoring.',
  },
  [APPLICATION_STATUS.ELIGIBILITY_EVALUATED]: {
    label: 'Eligibility Scored',
    badgeClass: 'badge-eligibility',
    stepIndex: 2,
    color: '#7c3aed',
    description: 'Algorithmic criteria evaluation completed against socio-economic limits.',
  },
  [APPLICATION_STATUS.FIELD_VERIFICATION]: {
    label: 'Field Verification Pending',
    badgeClass: 'badge-field',
    stepIndex: 3,
    color: '#d97706',
    description: 'Assigned to Field Inspection Officer for physical ground verification.',
  },
  [APPLICATION_STATUS.DISTRICT_REVIEW]: {
    label: 'District Review',
    badgeClass: 'badge-district',
    stepIndex: 4,
    color: '#ca8a04',
    description: 'Under administrative scrutiny by the District Magistrate / Collectorate.',
  },
  [APPLICATION_STATUS.FINANCE_APPROVAL]: {
    label: 'Finance Approval Pending',
    badgeClass: 'badge-finance',
    stepIndex: 5,
    color: '#4f46e5',
    description: 'Under final financial sanction and budget earmarking by Treasury Officer.',
  },
  [APPLICATION_STATUS.DISBURSEMENT_PLANNED]: {
    label: 'Disbursement Planned',
    badgeClass: 'badge-disbursement',
    stepIndex: 6,
    color: '#0891b2',
    description: 'Sanction approved. Milestone disbursement plan ready to formulate.',
  },
  [APPLICATION_STATUS.MILESTONE_PENDING]: {
    label: 'Milestones Active',
    badgeClass: 'badge-milestone',
    stepIndex: 7,
    color: '#2563eb',
    description: 'Staged disbursement milestones active. Awaiting compliance satisfaction.',
  },
  [APPLICATION_STATUS.DISBURSEMENT_IN_PROGRESS]: {
    label: 'Disbursement in Progress',
    badgeClass: 'badge-progress',
    stepIndex: 8,
    color: '#ea580c',
    description: 'Interim DBT milestone tranche funds released to beneficiary account.',
  },
  [APPLICATION_STATUS.FULLY_DISBURSED]: {
    label: 'Fully Disbursed',
    badgeClass: 'badge-progress',
    stepIndex: 9,
    color: '#16a34a',
    description: '100% of sanctioned grant disbursed via Treasury DBT UTR.',
  },
  [APPLICATION_STATUS.UTILIZATION_PENDING]: {
    label: 'Utilization Pending',
    badgeClass: 'badge-utilization',
    stepIndex: 9,
    color: '#ca8a04',
    description: 'Beneficiary required to submit expenditure receipts and utilization proofs.',
  },
  [APPLICATION_STATUS.COMPLETED]: {
    label: 'Grant Lifecycle Completed',
    badgeClass: 'badge-completed',
    stepIndex: 10,
    color: '#15803d',
    description: 'Full grant utilized, inspected, and verified on ground. Case closed.',
  },
  [APPLICATION_STATUS.REVERIFICATION_REQUIRED]: {
    label: 'Re-verification Required',
    badgeClass: 'badge-reverification',
    stepIndex: 3,
    color: '#c2410c',
    description: 'Discrepancy detected during verification; applicant or officer re-check needed.',
  },
  [APPLICATION_STATUS.REJECTED]: {
    label: 'Application Rejected',
    badgeClass: 'badge-rejected',
    stepIndex: -1,
    color: '#dc2626',
    description: 'Application rejected due to failed eligibility criteria or ground audit.',
  },
};

export const WORKFLOW_STAGES = [
  { key: 'DRAFT', title: 'Draft' },
  { key: 'SUBMITTED', title: 'Submitted' },
  { key: 'ELIGIBILITY_EVALUATED', title: 'Eligibility Scored' },
  { key: 'FIELD_VERIFICATION', title: 'Field Check' },
  { key: 'DISTRICT_REVIEW', title: 'District Review' },
  { key: 'FINANCE_APPROVAL', title: 'Finance Approval' },
  { key: 'DISBURSEMENT_PLANNED', title: 'Disbursement Plan' },
  { key: 'MILESTONE_PENDING', title: 'Milestones' },
  { key: 'DISBURSEMENT_IN_PROGRESS', title: 'Fund Release' },
  { key: 'UTILIZATION_PENDING', title: 'Utilization' },
  { key: 'COMPLETED', title: 'Completed' },
];
